budget_gui/budget_gui/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from test_app import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    url(r'^test_app/',include('test_app.urls'))
]

budget_gui/test_app/urls.py
from django.conf.urls import url
from test_app import views

# Template Tagging
app_name = 'test_app'

urlpatterns=[
    url(r'^$',views.index,name='index'),
	url(r'^relative/$',views.relative,name='relative'),
	url(r'^other/$',views.other,name='other'),
]

budget_gui/test_app/models.py
from django.db import models

# Create your models here.

budget_gui/test_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return(render(request,'test_app/index.html'))

def relative(request):
    return(render(request,'test_app/rel_url_tem.html'))

def other(request):
    return(render(request,'test_app/other.html'))

budget_gui/templates/test_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
<h1>welocme to base</h1>
  </body>
</html>

budget_gui/templates/test_app/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>welocme to index</h1>
  </body>
</html>

budget_gui/templates/test_app/other.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1> welcome to other </h1>
  </body>
</html>

budget_gui/templates/test_app/rel_url_tem.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1> welocme to relative url template </h1>
    <a href="{% url 'test_app:other' %}">other page</a>
    <h2> link for admin page</h2>
    <a href="{% url 'admin:index' %}">other page</a>
    <h3> link for index</h3>
    <a href="{% url 'index' %}">other page</a>
  </body>
</html>